FROM ollama/ollama:latest

WORKDIR /ollama_server

RUN apt-get update && apt-get install -y wget gnupg && \
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb && \
    dpkg -i cuda-keyring_1.1-1_all.deb && \
    apt-get update && \
    apt-get install -y cuda-toolkit && \
    rm -rf /var/lib/apt/lists/*

ENV PATH=/usr/local/cuda/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

EXPOSE 11434

COPY source/ollama/entrypoint.sh /ollama_server/entrypoint.sh
RUN chmod +x /ollama_server/entrypoint.sh

ENTRYPOINT ["/ollama_server/entrypoint.sh"]

